#!/bin/bash

# Keep commit subjects machine-readable for changelogs and review tooling.
COMMIT_MESSAGE=$(cat ${1})
VALID_COMMIT_PREFIXES="docs|fix|feat|chore|style|refactor|perf|test"
VALID_COMMIT_PREFIX_REGEX="^(${VALID_COMMIT_PREFIXES})(\((.*)\))?(!?)\: (.*)$"

echo "[DEBUG] Commit msg ~ ${COMMIT_MESSAGE}"
echo "[DEBUG] Valid commit prefixes ~ ${VALID_COMMIT_PREFIXES}"
echo "[DEBUG] Valid commit prefix regex ~ ${VALID_COMMIT_PREFIX_REGEX}"
echo "--- --- --- --- ---"

if ! [[ "${COMMIT_MESSAGE}" =~ ${VALID_COMMIT_PREFIX_REGEX} ]]; then
    echo "[ERROR] Commit message must begin with :~"
    echo "[ERROR] ${VALID_COMMIT_PREFIXES}:"
    echo "[ERROR] Example :~"
    echo "[ERROR] docs: Update the lovely documentation"
    exit 1
fi

exit 0
